"""Data-key conventions — auto-generated from aose-omics Rust crate.

This module is the Python mirror of `aose_omics::conventions`. The canonical
definitions live in Rust; this file is generated by calling the Rust crate's
`keys_as_json()` and never hand-edited. Import keys from here, never hard-code
string literals.

Regenerate: cargo run --bin omics-conventions-dump > this_file.py
(The bin will be added to aose-omics when the trait agent completes.)
"""

# TODO: These will be auto-generated. For now, manually sync with Rust:
LAYER_COUNTS = "counts"
LAYER_SPLICED = "spliced"
LAYER_UNSPLICED = "unspliced"

OBS_LEIDEN = "leiden"
OBS_CELLTYPE = "cell_type"
OBS_BATCH = "batch"
OBS_CONDITION = "condition"
OBS_DONOR = "donor"
OBS_TISSUE = "tissue"

OBSM_PCA = "X_pca"
OBSM_HARMONY = "X_pca_harmony"
OBSM_SCVI = "X_scVI"
OBSM_UMAP = "X_umap"
OBSM_TSNE = "X_tsne"
OBSM_LSI = "X_lsi"
OBSM_SPECTRAL = "X_spectral"
OBSM_MULTIVI = "X_multivi"
OBSM_SPATIAL = "spatial"
OBSM_PROPORTIONS = "proportions"

VAR_HIGHLY_VARIABLE = "highly_variable"
VAR_GENE_NAME = "gene_name"
VAR_GENE_ID = "gene_id"

# uns keys
UNS_NEIGHBORS = "neighbors"
UNS_UMAP = "umap"
UNS_RANK_GENES_GROUPS = "rank_genes_groups"

# Standard column types for validation
NUMERIC_OBS_KEYS = {"n_genes", "n_counts", "percent_mito", "doublet_score"}
CATEGORICAL_OBS_KEYS = {OBS_LEIDEN, OBS_CELLTYPE, OBS_BATCH, OBS_CONDITION, OBS_DONOR, OBS_TISSUE}

EMBEDDING_PREFIX = "X_"

def is_embedding_key(key: str) -> bool:
    """True if an obsm key is in the embedding namespace (X_*)."""
    return key.startswith(EMBEDDING_PREFIX)


def validate_counts_layer(adata, layer_key: str = LAYER_COUNTS):
    """Validate that the raw-counts layer exists. Fail loud (KeyError) if missing
    -- raw counts must live in layers['counts'] per convention, and several
    helpers (io.load_h5ad validation, seurat_v3 HVG) depend on it."""
    if layer_key not in adata.layers:
        available = list(adata.layers.keys())
        raise KeyError(
            f"Expected counts layer '{layer_key}' not found. "
            f"Available layers: {available}. "
            "Raw counts must be in layers['counts'] per convention."
        )
